apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: dev-
# nameSuffix: -v1
# commonLabels:
#   env: dev
# commonAnnotations:
#   author: alice
resources:
- deployment.yaml
images:
- name: nginx
  newTag: 1.8.0
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx
    path: patch.yaml