apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "16Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8080
