apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: my-app
  path: ../../patches/probe.yaml
