apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: my-app
  type: NodePort